# Generated by Django 5.2.8 on 2025-11-13 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0004_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('plan', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannually', 'Biannually'), ('yearly', 'Yearly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
