# Generated by Django 5.2.8 on 2025-11-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0005_gymmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymMember',
        ),
    ]
