# Generated by Django 5.2.8 on 2025-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0006_delete_gymmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_join', models.DateField()),
                ('plan', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannually', 'Biannually')], max_length=12)),
            ],
            options={
                'db_table': 'gymManagement_gymmember',
            },
        ),
    ]
