# Generated by Django 5.2.8 on 2025-11-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0007_gymmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='GymMember',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
