# Generated by Django 5.2.8 on 2025-11-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('validity_months', models.DecimalField(decimal_places=2, help_text='Enter validity in months (e.g., 1 for 1 month, 0.25 for 7 days).', max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
    ]
