# Generated by Django 5.2.8 on 2025-11-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0012_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
