# Generated by Django 5.2.8 on 2025-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0013_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Monthly', 'Monthly'), ('Biannually', 'Biannually'), ('Weekly', 'Weekly')], help_text='Plan type: Monthly, Biannually, or Weekly', max_length=100)),
                ('validity_months', models.DecimalField(choices=[(0.25, '7 Days (Weekly)'), (1, '1 Month (Monthly)'), (6, '6 Months (Biannually)')], decimal_places=2, help_text='Duration of the plan in months (1, 6, or 0.25 for 7 days)', max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price of the plan in Nu.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['validity_months', 'amount'],
            },
        ),
    ]
