# Generated by Django 5.2.8 on 2025-11-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0014_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['validity_months', 'amount'], 'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(help_text="e.g., 'Standard Monthly', 'Annual Premium'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity_months',
            field=models.DecimalField(choices=[(1, '1 Month'), (6, '6 Months (Biannually)'), (12, '12 Months (Annually)'), (0.25, '7 Days (Weekly)')], decimal_places=2, help_text='Duration of the plan in months (1, 6, 12, or 0.25 for 7 days)', max_digits=4),
        ),
    ]
