# Generated by Django 5.2.8 on 2025-11-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0015_alter_plan_options_alter_plan_plan_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
