# Generated by Django 5.2.8 on 2025-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0016_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannually', 'Biannually')], default='monthly', max_length=50, unique=True)),
                ('validity_months', models.FloatField(default=1.0, help_text='Validity period in months (e.g., 0.25 for 7 days, 1.0 for 1 month).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Nu.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan Detail',
                'verbose_name_plural': 'Plan Details',
                'ordering': ['validity_months'],
            },
        ),
    ]
