# Generated by Django 5.2.8 on 2025-11-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0018_member_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
