# Generated by Django 5.2.8 on 2025-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0019_remove_payment_member_delete_member_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('member_id', models.CharField(max_length=50, unique=True, verbose_name='Member ID')),
                ('plan', models.CharField(choices=[('weekly', '1 Week'), ('monthly', '1 Month'), ('biannually', '6 Months'), ('yearly', '1 Year')], default='monthly', max_length=20, verbose_name='Plan Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount (Nu.)')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
