# Generated by Django 5.2.8 on 2025-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0022_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=50),
        ),
    ]
